config/routes.rb
Goal::Application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    resources :objectives, only: [:create, :update, :destroy]
  end
  resource :session, only: [:new, :create, :destroy]
end

app/models/admin.rb
class Admin < User

end

app/models/objective.rb
class Objective < ActiveRecord::Base
  attr_accessible :body, :completed

  validates :body, presence: true

  belongs_to :user, inverse_of: :objectives

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  attr_accessible :username, :password
  validates :password_digest, :session_token, :username, presence: true
  after_initialize :ensure_session_token

  has_many :objectives, inverse_of: :user

  def has_objectives?
    !self.objectives.empty?
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil unless !!user

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

class Admin < User

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

    def new

    end

    def create
      @admin = Admin.new(params[:admin])

      if @admin.save
        login_admin!(@admin)
        redirect_to @admin
      else
        render :new
      end
    end

    def show
      @admin = Admin.find(params[:id])
    end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @user.objectives.new(params[:objective])

    if @user.save
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to @user
    end
  end

  def update
    @objective = Objective.find(params[:id])

    if @objective.update_attributes(params[:objective])
      redirect_to @objective.user
    else
      flash[:errors] = @objective.errors.full_messages
      redirect_to @objective.user
    end
  end

  def destroy
    @objective = Objective.find(params[:id])
    @objective.destroy
    redirect_to @objective.user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )

    if @user
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "invalid username/password"
      render :new
    end
  end

  def destroy
    log_out
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user!(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"<%= form_authenticity_token %>\">".html_safe
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goal</title>
</head>
<body>

  <% if logged_in? %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
  <% end %>

  <%= flash[:errors]%>
  <%= yield %>

</body>
</html>

app/views/objectives/_complete.html.erb
<form action="<%= user_objective_url(user,objective) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="put">

  <input type="hidden" name="objective[completed]" value="true">

  <input type="submit" value="Complete Goal">
</form>

app/views/objectives/_edit.html.erb
<form action="<%= user_objective_url(user,objective) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="put">
  <label for="goal">Goal</label><input type="text" name="objective[body]" id="goal" value="<%= objective.body %>">


  <br>
  <input type="submit" value="Update Goal">
</form>

app/views/users/new.html.erb
<h1> Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Username
    <input type="text" name="user[username]"></label>
    <br>
    <label>Password
      <input type="password" name="user[password]"></label>

      <input type="submit" value="Sign Up">

    </form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<form action="<%= user_objectives_url(@user) %>" method="POST">

  <label>
    New Goal
    <input type="text" name="objective[body]">
  </label>

  <input type="submit" value="Create Goal">

</form>

<% if @user.has_objectives? %>
  <ul>
    <% @user.objectives.each do |objective| %>
      <li><%= objective.body %><%= ": Completed" if objective.completed? %></li>
      <% if current_user == @user || current_user.type == "Admin" %>
        <% unless objective.completed %>
          <%= render "objectives/edit", user: @user, objective: objective %>
          <%= render "objectives/complete", user: @user, objective: objective %>
        <% end %>

        <%= button_to "Delete Goal", user_objective_url(@user,objective), method: :delete %>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>
    No goals
  </p>
<% end %>